### ISSUE TITLE
How To Build Query Builder 

### ISSUE THREAD

**Issue by deepaktina** [hagnat/distributed-studies#1]
Rest API parameters to query Couchbase - Do you have any views on this? We tried using views and n1ql queries which seems ok but may be difficult to write for complex queries. ( We did think of directly going to Postgres for complex queries ) - Do you think this approach makes sense?

**Comment by hagnat** [comment]
You are not supposed to write complicated queries in your CouchbaseService. If you need to write a map reduce, you are either trying to squeeze too much from the CB server, or you are writting too little on it.

**Comment by hagnat** [comment]
Take for example a query for `ProductRepository::listByCategory('food');`. On your first run, you will query the PostgreSqlService for this query, it will return a collection of products which, when you proceed to insert the response on the CouchbaseService, will be stored in the key 'products:bycategory:food'.

**Comment by hagnat** [comment]
n1ql has its use when you are querying information that is not replicated on a relation database due the sheer volume of information. When I was developing a recommendation system for a fashion store, we were considering using n1ql to query the millions of user collected data we created in a daily basis.
