### ISSUE TITLE
How do we ensure the data in Couchbase and Postgres are in Synch

### ISSUE THREAD

**Issue by deepaktina** [hagnat/distributed-studies#2]
As write to Postgres is asynch. how do we ensure that Postgres and Couchbase are in synch?

**Comment by hagnat** [comment]
as i mention in #3, the main idea is to use the database connection as a service linked to a chain-of-responsability design. 

To read information from the chain, you start on the left side of the chain, by querying the CouchbaseService. If the information is not there, you follow the chain up to its end, where it will meet your PostgreSqlService. Once the information is found, it is propagated to the previous layers of the chain, for future use.

**Comment by hagnat** [comment]
To write information, however, you will go through both ends of the chain, asynchronaly. You will query the CouchbaseService to store the information on it - and stop there - at the same time you fire a message to your queue server for a update on the PostgreSqlService. Once that message gets processed, your PostgreSqlService will follow the chain, and update all other services about any chances that the entity might further get that first layer wasn't expecting - cuz the business logic IS ONLY on the backend layer, not on the same layer as the one used by the CouchbaseService -

**Comment by hagnat** [comment]
To prevent the PostgreSqlService from updating the other services on its chain, you can always use some sort of hashing, and compare if the information that pgsqlService is trying to overwrite on the CbService is not outdated.
