### ISSUE TITLE
Full text search in your proposed architecture 

### ISSUE THREAD

**Issue by deepaktina** [hagnat/distributed-studies#4]
Using Elastic Search for full text search - Any thoughts on this? And how do we direct the full text search queries to couchbase vs Elastic Search?

**Comment by hagnat** [comment]
I used Lucene for my Grad Thesis, on a genetic algorithm improved search engine. It had really poor results, but the blame is easily shifted to my GA strategy, not Lucene itself. Sadly, that's all the experience i have with anything that remotely resembles Elastic Search.

Maybe I should think about including ES in some part of my proposed architecture for further studies.
